language: node_js
cache: yarn
node_js:
  - "6"
#  - "7" NOT SUPPORTED BY fs-extra
  - "8"
  - "9"
  - "10"
install:
    - yarn add --dev codecov snyk coveralls
script:
  - yarn cover
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
  - ./node_modules/.bin/codecov
  - ./node_modules/.bin/snyk test
